controller_list:
  - name: magician_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    allowed_execution_duration_scaling: 1.2
    allowed_goal_duration_margin: 2
    joints:
      - magician_joint1
      - magician_joint2
      - magician_joint3
  - name: manipulator_controller
    type: position_controllers/JointPositionController
    allowed_execution_duration_scaling: 1.2
    allowed_goal_duration_margin: 2
    joints:
      - magician_joint1
      - magician_joint2
      - magician_joint3

            
  - name: joint_state_controller
    type: joint_state_controller/JointStateController
    publish_rate: 50

