controller_list:
  - name: magician_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - magician_joint1
      - magician_joint2
      - magician_joint3
  - name: manipulator_controller
    type: position_controllers/JointPositionController
    joints:
      - magician_joint1
      - magician_joint2
      - magician_joint3
      
  - name: joint_state_controller
    type: joint_state_controller/JointStateController
    publish_rate: 50

