controller_list:
  - name: fake_manipulator_controller
    joints:
      - magician_joint1
      - magician_joint2
      - magician_joint3
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home