magician_arm_controller:
  type: position_controllers/JointGroupPositionController #???
  #joint: gripper_joint ???
  joints:
     - magician_joint1
     - magician_joint2
     - magician_joint3
  gains:
    magician_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    magician_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    magician_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

